/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import ticket.booking.entities.Train;
import ticket.booking.entities.User;
import ticket.booking.services.TrainService;
import ticket.booking.services.UserBookingService;

import java.io.IOException;
import java.util.List;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        try {
            System.out.println("********** 🚄 Ticket Booking System 🛤️ **********");

            UserBookingService userBookingService;

            try {
                userBookingService = new UserBookingService();
            } catch (IOException ex) {
                System.out.println("Error occurred while initializing the service 😟");
                return;
            }

            Scanner sc = new Scanner(System.in);
            int option = 0;
            List<Train> matchingTrains = null;

            while (option != 7) {
                System.out.println("Choose option");
                System.out.println("1. Sign up");
                System.out.println("2. Login");
                System.out.println("3. Fetch Bookings");
                System.out.println("4. Search Trains");
                System.out.println("5. Book a Seat");
                System.out.println("6. Cancel my Booking");
                System.out.println("7. Exit the App");

                option = sc.nextInt();
                sc.nextLine();
                String name, password;

                switch (option) {
                    case 1:
                        System.out.println("Enter your Name 🙏");
                        name = sc.nextLine();

                        System.out.println("Enter your password 🧑‍💻");
                        password = sc.next();

                        User newUser = new User(name, password);

                        userBookingService.signUp(newUser);
                        System.out.println("\nUser signed up successfully 🚀\n");
                        break;

                    case 2:
                        System.out.println("Enter your Name 🐣");
                        name = sc.nextLine();

                        System.out.println("Enter your password 🗝️");
                        password = sc.next();

                        if (userBookingService.loginUser(name, password)) {
                            System.out.println("\nUser " + name + " logged in successfully ✅\n");
                        } else {
                            System.out.println("\nUh-hu! Invalid credentials. Please try again ❌\n");
                        }
                        break;

                    case 3:
                        System.out.println("Fetching your bookings... 🤔");
                        userBookingService.fetchBooking();
                        System.out.println();
                        break;

                    case 4:
                        System.out.println("Enter source station 🚉");
                        String source = sc.next();

                        System.out.println("Enter destination station 🚉");
                        String destination = sc.next();

                        matchingTrains = userBookingService.getTrains(source, destination);
                        TrainService.printTrainDetails(matchingTrains);

                        break;

                    case 5:
                        if (matchingTrains == null) {
                            System.out.println("Please search for trains first (Press 4️⃣) 🚉");
                            break;
                        }

                        System.out.println("Enter the train number you want to book a seat in (1, 2, 3...) 🚉");
                        int trainNumber = sc.nextInt();
                        while (trainNumber < 1 || trainNumber > matchingTrains.size()) {
                            System.out.println("Invalid train number. Please try again!!!");
                            trainNumber = sc.nextInt();
                        }

                        Train train = matchingTrains.get(trainNumber - 1);
                        System.out.println("Seat availability for the selected train 💺");
                        List<List<Integer>> lists = userBookingService.fetchSeats(train);

                        for (List<Integer> list: lists) {
                            System.out.println(list);
                        }

                        System.out.println("Select the seat by typing the row and column");
                        System.out.println("Enter row number");
                        int row = sc.nextInt();
                        System.out.println("Enter column number");
                        int column = sc.nextInt();

                        System.out.println("Booking your seat...");

                        Boolean booked = userBookingService.bookSeat(matchingTrains.get(trainNumber - 1), row, column);
                        if (booked.equals(Boolean.TRUE)) {
                            System.out.println("Seat booked successfully 🎉");
                        } else {
                            System.out.println("Seat booking failed 😟");
                        }

                        break;

                    default:
                        System.out.println("Invalid option. Please try again!!!");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Error: " + e.getMessage());
        }
    }
}
